# for local development
version: "3.8"
services:
  quasar:
    build:
      context: .
      target: "develop-stage"
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    command: /bin/sh -c "yarn && yarn dev"
